import { useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { Plus, Trash2, Bell, BellRing, Download, Upload } from "lucide-react";
import { api } from "@/api/client";
import { Card, CardHeader } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { MarketBadge } from "@/components/ui/MarketBadge";
import { ErrorState } from "@/components/ui/ErrorState";
import { changeClass, fmt, fmtPct } from "@/lib/cn";
import { useT } from "@/lib/i18n";

export function Watchlist() {
  const t = useT();
  const qc = useQueryClient();
  const watch = useQuery({ queryKey: ["watch"], queryFn: api.watchlist, refetchInterval: 30_000 });
  const alerts = useQuery({ queryKey: ["alerts"], queryFn: api.alerts });

  const [symbol, setSymbol] = useState("");
  const addItem = useMutation({
    mutationFn: () => api.watchAdd(symbol),
    onSuccess: () => { setSymbol(""); qc.invalidateQueries({ queryKey: ["watch"] }); },
  });
  const remItem = useMutation({
    mutationFn: (id: number) => api.watchRemove(id),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["watch"] }),
  });

  const [alertSym, setAlertSym] = useState("");
  const [metric, setMetric] = useState("price");
  const [op, setOp] = useState(">");
  const [threshold, setThreshold] = useState<number | "">("");
  const addAlert = useMutation({
    mutationFn: () => api.alertAdd({ symbol: alertSym, metric, op, threshold: Number(threshold) }),
    onSuccess: () => { setAlertSym(""); setThreshold(""); qc.invalidateQueries({ queryKey: ["alerts"] }); },
  });
  const remAlert = useMutation({
    mutationFn: (id: number) => api.alertRemove(id),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["alerts"] }),
  });
  const evaluate = useMutation({ mutationFn: () => api.alertEvaluate() });

  const fileRef = useRef<HTMLInputElement>(null);
  const [importMsg, setImportMsg] = useState<{ kind: "ok" | "err"; text: string } | null>(null);

  /**
   * Download a fillable template — three example tickers across the three
   * markets, with a `_help` field so editors-with-no-Argus-knowledge see
   * the schema. Users edit the file, then re-import.
   */
  function downloadTemplate() {
    const tpl = {
      app: "argus",
      version: 1,
      type: "watchlist",
      _help:
        "Replace the items below with your own. `symbol` accepts US tickers (AAPL), " +
        "A-share 6-digit codes (600519 / 000858), or HK codes with the .HK suffix " +
        "(0700.HK). `note` is free text and can be omitted.",
      items: [
        { symbol: "AAPL",      note: "Example US ticker" },
        { symbol: "600519",    note: "Example A-share — Kweichow Moutai" },
        { symbol: "0700.HK",   note: "Example HK ticker — Tencent" },
      ],
      disclaimer: "Generated by Argus. Research and education only — not investment advice.",
    };
    const blob = new Blob([JSON.stringify(tpl, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "argus-watchlist-template.json";
    a.click();
    URL.revokeObjectURL(url);
  }

  /**
   * Import accepts EITHER:
   *   1) Argus watchlist JSON (the template, edited)
   *   2) plain text — one symbol per line, with optional `# comment` or
   *      `// comment` per line.
   * Duplicates / failed adds are silently skipped so a partial list still
   * imports the rest.
   */
  async function importFile(file: File) {
    setImportMsg(null);
    let symbols: string[] = [];
    const notes: Record<string, string> = {};

    let text = "";
    try {
      text = await file.text();
    } catch {
      setImportMsg({ kind: "err", text: t("watch.importErr") });
      return;
    }

    // Try JSON first.
    try {
      const parsed = JSON.parse(text);
      if (parsed && parsed.type === "watchlist" && Array.isArray(parsed.items)) {
        for (const it of parsed.items) {
          const sym = String(it?.symbol ?? "").trim();
          if (!sym) continue;
          symbols.push(sym);
          if (it?.note) notes[sym] = String(it.note);
        }
      } else {
        throw new Error("not a watchlist json");
      }
    } catch {
      // Fall back to plain text — one symbol per line, strip comments.
      symbols = text
        .split(/\r?\n/)
        .map((l) => l.split(/[#]|\/\//)[0].trim())
        .filter(Boolean);
    }

    if (symbols.length === 0) {
      setImportMsg({ kind: "err", text: t("watch.importErr") });
      return;
    }

    let added = 0;
    for (const sym of symbols) {
      try {
        await api.watchAdd(sym, notes[sym] ?? "");
        added += 1;
      } catch {
        /* skip duplicates / failures, continue */
      }
    }
    qc.invalidateQueries({ queryKey: ["watch"] });
    setImportMsg({ kind: "ok", text: t("watch.imported", { n: added }) });
  }

  return (
    <div className="px-6 py-6 grid lg:grid-cols-3 gap-6">
      <div className="lg:col-span-2 space-y-6">
        <Card>
          <CardHeader
            title={t("watch.title")}
            subtitle={t("watch.subtitle")}
            right={
              <div className="flex gap-1.5">
                <Button variant="outline" onClick={downloadTemplate} className="!px-3 !py-1 text-xs">
                  <Download className="w-3 h-3" /> {t("watch.template")}
                </Button>
                <Button variant="outline" onClick={() => fileRef.current?.click()} className="!px-3 !py-1 text-xs">
                  <Upload className="w-3 h-3" /> {t("watch.import")}
                </Button>
                <input
                  ref={fileRef}
                  type="file"
                  accept="application/json,text/plain,.json,.txt,.csv"
                  className="hidden"
                  onChange={(e) => {
                    const f = e.target.files?.[0];
                    if (f) importFile(f);
                    e.target.value = "";
                  }}
                />
              </div>
            }
          />
          <div className="text-[11px] text-zinc-500 -mt-2 mb-3">{t("watch.importHint")}</div>
          {watch.isError && (
            <div className="mb-3"><ErrorState compact error={watch.error} onRetry={() => watch.refetch()} /></div>
          )}
          {importMsg && (
            <div className={"text-xs mb-3 " + (importMsg.kind === "ok" ? "text-emerald-400" : "text-amber-300")}>
              {importMsg.text}
            </div>
          )}
          <form
            onSubmit={(e) => { e.preventDefault(); if (symbol.trim()) addItem.mutate(); }}
            className="flex gap-2 mb-4"
          >
            <input
              value={symbol}
              onChange={(e) => setSymbol(e.target.value)}
              placeholder={t("watch.placeholder")}
              className="flex-1 h-10 px-3 rounded-lg glass text-sm outline-none"
            />
            <Button type="submit"><Plus className="w-3.5 h-3.5" /> {t("watch.add")}</Button>
          </form>

          <div className="overflow-x-auto -mx-5">
            <table className="w-full text-sm">
              <thead className="text-[10px] uppercase tracking-wider text-zinc-500">
                <tr className="border-b border-white/5">
                  <th className="text-left px-5 py-2">{t("screener.col.symbol")}</th>
                  <th className="text-left px-3 py-2">{t("screener.col.name")}</th>
                  <th className="text-left px-3 py-2">{t("screener.col.market")}</th>
                  <th className="text-right px-3 py-2">{t("screener.col.price")}</th>
                  <th className="text-right px-3 py-2">{t("screener.col.change")}</th>
                  <th className="text-right px-5 py-2"></th>
                </tr>
              </thead>
              <tbody>
                {(watch.data?.items ?? []).map((it: any) => (
                  <tr key={it.id} className="border-b border-white/[0.03] hover:bg-white/[0.03]">
                    <td className="px-5 py-2 font-mono">
                      <Link to={`/stock/${encodeURIComponent(it.symbol)}`} className="text-cyan-300 hover:text-cyan-200">
                        {it.symbol}
                      </Link>
                    </td>
                    <td className="px-3 py-2 text-zinc-300 max-w-[14rem] truncate">{it.name}</td>
                    <td className="px-3 py-2"><MarketBadge market={it.market} /></td>
                    <td className="px-3 py-2 text-right tabular-nums">{fmt(it.quote?.price)}</td>
                    <td className={`px-3 py-2 text-right tabular-nums font-medium ${changeClass(it.quote?.change_pct)}`}>
                      {fmtPct(it.quote?.change_pct)}
                    </td>
                    <td className="px-5 py-2 text-right">
                      <button
                        onClick={() => remItem.mutate(it.id)}
                        className="text-zinc-500 hover:text-rose-400 transition-colors"
                      ><Trash2 className="w-4 h-4" /></button>
                    </td>
                  </tr>
                ))}
                {!watch.isLoading && (watch.data?.items?.length ?? 0) === 0 && (
                  <tr><td colSpan={6} className="px-5 py-10 text-center text-zinc-500">{t("watch.empty")}</td></tr>
                )}
              </tbody>
            </table>
          </div>
        </Card>
      </div>

      <div className="space-y-6">
        <Card>
          <CardHeader title={t("watch.alerts.title")} subtitle={t("watch.alerts.subtitle")} />
          <form
            onSubmit={(e) => { e.preventDefault(); if (alertSym.trim() && threshold !== "") addAlert.mutate(); }}
            className="space-y-2 mb-4"
          >
            <input
              value={alertSym}
              onChange={(e) => setAlertSym(e.target.value)}
              placeholder={t("watch.alerts.symbol")}
              className="w-full h-10 px-3 rounded-lg glass text-sm outline-none"
            />
            <div className="grid grid-cols-3 gap-2">
              <select value={metric} onChange={(e) => setMetric(e.target.value)} className="h-10 px-2 rounded-lg glass text-sm outline-none">
                <option value="price">{t("watch.alerts.metric.price")}</option>
                <option value="change_pct">{t("watch.alerts.metric.changePct")}</option>
                <option value="rsi_14">{t("watch.alerts.metric.rsi")}</option>
              </select>
              <select value={op} onChange={(e) => setOp(e.target.value)} className="h-10 px-2 rounded-lg glass text-sm outline-none">
                <option value=">">{">"}</option>
                <option value=">=">{"≥"}</option>
                <option value="<">{"<"}</option>
                <option value="<=">{"≤"}</option>
              </select>
              <input
                value={threshold}
                onChange={(e) => setThreshold(e.target.value === "" ? "" : Number(e.target.value))}
                type="number" step="any"
                placeholder={t("watch.alerts.value")}
                className="h-10 px-2 rounded-lg glass text-sm outline-none"
              />
            </div>
            <Button type="submit" className="w-full justify-center"><Bell className="w-3.5 h-3.5" /> {t("watch.alerts.add")}</Button>
          </form>

          <div className="space-y-2 max-h-72 overflow-y-auto pr-1">
            {(alerts.data?.alerts ?? []).map((a: any) => (
              <div key={a.id} className="flex items-center justify-between text-xs glass rounded-lg px-3 py-2">
                <div>
                  <span className="font-mono text-zinc-100">{a.symbol}</span>
                  <span className="text-zinc-500"> · {a.metric} {a.op} {a.threshold}</span>
                </div>
                <button onClick={() => remAlert.mutate(a.id)} className="text-zinc-500 hover:text-rose-400">
                  <Trash2 className="w-3.5 h-3.5" />
                </button>
              </div>
            ))}
            {!alerts.isLoading && (alerts.data?.alerts?.length ?? 0) === 0 && (
              <div className="text-xs text-zinc-500 text-center py-6">{t("watch.alerts.empty")}</div>
            )}
          </div>

          <Button onClick={() => evaluate.mutate()} variant="outline" className="w-full justify-center mt-3">
            <BellRing className="w-3.5 h-3.5" /> {t("watch.alerts.evaluate")}
          </Button>
          {evaluate.data && (
            <div className="mt-2 text-xs">
              {evaluate.data.triggered.length === 0
                ? <span className="text-zinc-500">{t("watch.alerts.none")}</span>
                : <span className="text-emerald-400">{t("watch.alerts.triggered", { n: evaluate.data.triggered.length })}</span>}
            </div>
          )}
        </Card>
      </div>
    </div>
  );
}
