/** Shared helpers for "copy / export / share" flows.
 *
 * Every payload that can leave the app (clipboard, file, link) must go through
 * one of these helpers so the disclaimer and "no leakage" rules are applied
 * in a single place. Never include API keys or absolute paths in shared
 * output.
 */

export const SHARE_DISCLAIMER_EN =
  "Generated by Argus. Research & education only — not investment advice.";
export const SHARE_DISCLAIMER_ZH =
  "本内容由 Argus 生成，仅供研究与教育用途，不构成投资建议。";

export function disclaimer(lang: string): string {
  return lang === "zh" ? SHARE_DISCLAIMER_ZH : SHARE_DISCLAIMER_EN;
}

export async function copyText(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

export function downloadText(filename: string, text: string, mime = "text/markdown") {
  const blob = new Blob([text], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

/** Build a public, shareable URL for the current stock page. Strips query
 * strings and any hash to avoid leaking local state. */
export function stockShareUrl(symbol: string): string {
  const u = new URL(window.location.href);
  u.search = "";
  u.hash = "";
  u.pathname = `/stock/${encodeURIComponent(symbol)}`;
  return u.toString();
}
